;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Sep 29 2025
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

DATA SEGMENT 
 PORTA EQU 0F0H ; PORTA address 
 PORTB EQU 0F2H ; PORTB address 
 PORTC EQU 0F4H ; PORTC address 
 DATA ENDS 
 
 CODE SEGMENT 
 MOV AX, DATA 
 MOV DS, AX ; set the Data Segment address 
 
 ORG 0000H 
 
 START: 
;--------------------------------------------
 MOV DX, PORTB ; set port address of PORTB 
 MOV AL, 01101111B ;7 SEGMENT BCD FOR 9
 OUT DX, AL ; send to PORTB DISPLAYS 9
;---------------------------------------------
 
;============================================================
MAIN_LOOP:
 MOV DX, PORTC ; PORTC is used since the port is input 
 IN AL, DX ; read an 8-bit from PORTC and store it AL
 
 MOV DX, PORTA ; set port address of PORTA
 OUT DX, AL ; send the value read from PORTC to PORTA
 
 ; less lag
 MOV CX, 100
DELAY:
 NOP
 LOOP DELAY
 
 JMP MAIN_LOOP ; continuously read and update
;=============================================================
 
 
 CODE ENDS 
 END