;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Oct 7 2024
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

DATA SEGMENT
           PORTA  EQU  700H  ;INPUT ADDRESS
           PORTB  EQU  701H   ;OUTPUT ADDRESS

DATA    ENDS


CODE    SEGMENT PUBLIC 'CODE'
        MOV  AX, DATA
    MOV  DS,  AX

CLEARDISP:
    MOV DX, PORTB
    MOV AL, 0H
    OUT DX, AL
    JMP START
    
    
START: 
    MOV DX, PORTB
    MOV AL, 0H
    OUT DX, AL
    
    MOV DX, PORTB
    MOV AL, 0H
    OUT DX, AL
    
    MOV  DX, PORTA
    IN AL, DX
    
    CMP AL,2H
    JE ROUTINE1
    
    CMP AL, 4H
    JE ROUTINE2
    
    MOV DX, PORTB
    MOV AL, 0H
    OUT DX, AL
    JMP START
    
    JMP  START
    
    ; ROUTINE 1: Sequence triggered when input = 2H
    ROUTINE1:
    
    STEP1_WAIT:
    MOV  DX, PORTB
    MOV AL, 00000001B      ; Output pattern: bit 0
    OUT DX, AL

    MOV DX, PORTA
    IN AL, DX

    CMP AL, 2H
    JE STEP2_WAIT
    JNE STEP1_WAIT
    
    STEP2_WAIT:
    MOV  DX, PORTB
    MOV AL, 00100000B      ; Output pattern: bit 5
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 2H
    JE STEP3_WAIT
    JNE STEP2_WAIT
    
    STEP3_WAIT:
    MOV  DX, PORTB
    MOV AL, 00000100B      ; Output pattern: bit 2
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 2H
    JE STEP4_WAIT
    JNE STEP3_WAIT
      
    STEP4_WAIT:
    MOV  DX, PORTB
    MOV AL, 10000000B      ; Output pattern: bit 7
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 2H
    JE STEP5_WAIT
    JNE STEP4_WAIT
      
    STEP5_WAIT:
    MOV  DX, PORTB
    MOV AL, 00001000B      ; Output pattern: bit 3
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 2H
    JE STEP6_WAIT
    JNE STEP5_WAIT
      
    STEP6_WAIT:
    MOV  DX, PORTB
    MOV AL, 01000000B      ; Output pattern: bit 6
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 2H
    JE STEP7_WAIT
    JNE STEP6_WAIT
      
    STEP7_WAIT:
    MOV  DX, PORTB
    MOV AL, 00000010B      ; Output pattern: bit 1
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 2H
    JE STEP8_WAIT
    JNE STEP7_WAIT
    
    STEP8_WAIT:
    MOV  DX, PORTB
    MOV AL, 00010000B      ; Output pattern: bit 4
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 2H
    JE STEP9_WAIT
    JNE STEP8_WAIT
    
    STEP9_WAIT:
    MOV  DX, PORTB
    MOV AL, 00000001B      ; Output pattern: bit 0 (cycle back)
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX
    
    CMP AL, 2H
    JE START
    JNE STEP9_WAIT
    
    ; ROUTINE 2: Sequence triggered when input = 4H
    ROUTINE2:
    
    SEQ2_STEP1_WAIT:
    MOV DX, PORTB
    MOV AL, 00010001B      ; Output pattern: bits 0,4
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 4H
    JE SEQ2_STEP2_WAIT
    JNE SEQ2_STEP1_WAIT

    SEQ2_STEP2_WAIT:
    MOV DX, PORTB
    MOV AL, 00010010B      ; Output pattern: bits 1,4
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 4H
    JE SEQ2_STEP3_WAIT
    JNE SEQ2_STEP2_WAIT

    SEQ2_STEP3_WAIT:
    MOV DX, PORTB
    MOV AL, 00110000B      ; Output pattern: bits 4,5
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 4H
    JE SEQ2_STEP4_WAIT
    JNE SEQ2_STEP3_WAIT
    
    SEQ2_STEP4_WAIT:
    MOV DX, PORTB
    MOV AL, 00100010B      ; Output pattern: bits 1,5
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 4H
    JE SEQ2_STEP5_WAIT
    JNE SEQ2_STEP4_WAIT
    
    SEQ2_STEP5_WAIT:
    MOV DX, PORTB
    MOV AL, 00100100B      ; Output pattern: bits 2,5
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 4H
    JE SEQ2_STEP6_WAIT	 
    JNE SEQ2_STEP5_WAIT

    SEQ2_STEP6_WAIT:
    MOV DX, PORTB
    MOV AL, 01100000B      ; Output pattern: bits 5,6
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX
    CMP AL, 4H
    JE SEQ2_STEP7_WAIT
    JNE SEQ2_STEP6_WAIT

    SEQ2_STEP7_WAIT:
    MOV DX, PORTB
    MOV AL, 01000100B      ; Output pattern: bits 2,6
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 4H
    JE SEQ2_STEP8_WAIT
    JNE SEQ2_STEP7_WAIT

    SEQ2_STEP8_WAIT:
    MOV DX, PORTB
    MOV AL, 01000100B      ; Output pattern: bits 2,6 (repeated)
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 4H
    JE SEQ2_STEP9_WAIT
    JNE SEQ2_STEP8_WAIT

    SEQ2_STEP9_WAIT:
    MOV DX, PORTB
    MOV AL, 01001000B      ; Output pattern: bits 3,6
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 4H
    JE SEQ2_STEP10_WAIT
    JNE SEQ2_STEP9_WAIT

    SEQ2_STEP10_WAIT:
    MOV DX, PORTB
    MOV AL, 11000000B      ; Output pattern: bits 6,7
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX	
    CMP AL, 4H
    JE SEQ2_STEP11_WAIT
    JNE SEQ2_STEP10_WAIT
     
    SEQ2_STEP11_WAIT:
    MOV DX, PORTB
    MOV AL, 10001000B      ; Output pattern: bits 3,7
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX
    
    CMP AL, 4H
    JE SEQ2_STEP12_WAIT	
    JNE SEQ2_STEP11_WAIT
    
    SEQ2_STEP12_WAIT:
    MOV DX, PORTB
    MOV AL, 10000100B      ; Output pattern: bits 2,7
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 4H
    JE SEQ2_STEP13_WAIT
    JNE SEQ2_STEP12_WAIT

    SEQ2_STEP13_WAIT:
    MOV DX, PORTB
    MOV AL, 11000000B      ; Output pattern: bits 6,7
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 4H
    JE SEQ2_STEP14_WAIT
    JNE SEQ2_STEP13_WAIT
    
    SEQ2_STEP14_WAIT:
    MOV DX, PORTB
    MOV AL, 01000100B      ; Output pattern: bits 2,6
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 4H
    JE SEQ2_STEP15_WAIT
    CMP AL, 5H
    JNE SEQ2_STEP14_WAIT	

    SEQ2_STEP15_WAIT:
    MOV DX, PORTB
    MOV AL, 01000010B      ; Output pattern: bits 1,6
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 4H
    JE SEQ2_STEP16_WAIT
    JNE SEQ2_STEP15_WAIT
    
    SEQ2_STEP16_WAIT:
    MOV DX, PORTB
    MOV AL, 01100000B      ; Output pattern: bits 5,6
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX
    
    CMP AL, 4H
    JE SEQ2_STEP17_WAIT
    JNE SEQ2_STEP16_WAIT

    SEQ2_STEP17_WAIT:
    MOV DX, PORTB
    MOV AL, 00100010B      ; Output pattern: bits 1,5
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 4H
    JE SEQ2_STEP18_WAIT
    JNE SEQ2_STEP17_WAIT
    
    SEQ2_STEP18_WAIT:
    MOV DX, PORTB
    MOV AL, 00100001B      ; Output pattern: bits 0,5
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX
    
    CMP AL, 4H
    JE SEQ2_STEP19_WAIT
    CMP AL, 5H
    JNE SEQ2_STEP18_WAIT
    
    SEQ2_STEP19_WAIT:
    MOV DX, PORTB
    MOV AL, 00110000B      ; Output pattern: bits 4,5
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX

    CMP AL, 4H
    JE SEQ2_STEP20_WAIT
    JNE SEQ2_STEP19_WAIT

    SEQ2_STEP20_WAIT:
    MOV DX, PORTB
    MOV AL, 00010001B      ; Output pattern: bits 0,4
    OUT DX, AL
    MOV DX, PORTA
    IN AL, DX
    
    CMP AL, 4H
    JE START
    JNE SEQ2_STEP20_WAIT
     
HERE:
    NOP
    JMP  HERE
CODE    ENDS
END