;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Wed Oct 30 2024
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
PROCED1 SEGMENT
ISR4 PROC FAR
ASSUME CS:PROCED1, DS:DATA
ORG 01000H
	 PUSHF
	 PUSH AX
	 PUSH DX
	 
	 MOV AL, FLAG_TEST
	 INC AL
	 MOV FLAG_TEST, AL
	 
	 POP DX
	 POP AX
	 POPF
	 IRET
ISR4 ENDP
PROCED1 ENDS

PROCED2 SEGMENT
ISR6 PROC FAR
ASSUME CS:PROCED2, DS:DATA
ORG 02000H
	 PUSHF
	 PUSH AX
	 PUSH DX
	 
	 MOV FLAG_EMERGENCY, 1
	 
	 POP DX
	 POP AX
	 POPF
	 IRET
ISR6 ENDP
PROCED2 ENDS

DATA SEGMENT
ORG 03000H
	 PORTA EQU 0F0H
	 PORTB EQU 0F2H
	 PORTC EQU 0F4H
	 COM_REG1 EQU 0F6H
	 
	 PORTD EQU 0F8H
	 PORTE EQU 0FAH
	 PORTF EQU 0FCH
	 COM_REG2 EQU 0FEH
	 
	 PIC1 EQU 0E0H
	 PIC2 EQU 0E2H
	 ICW1 EQU 13H
	 ICW2 EQU 84H
	 ICW4 EQU 03H
	 OCW1_84H EQU 0EFH
	 OCW1_86H EQU 0BFH
	 
	 TIMER EQU 0E8H
	 WRITE EQU 0EAH
	 
	 FLAG_TEST DB 0
	 FLAG_EMERGENCY DB 0
	 
	 MENU1 DB "[1] Coke Large", "$"
	 MENU2 DB "[2] Coke Medium", "$"
	 MENU3 DB "[3] Sprite Large", "$"
	 MENU4 DB "[4] Sprite Medium", "$"
	 MSG1 DB "Testing valves...", "$"
	 MSG2 DB "Emergency Stop!", "$"
	 DISPENSINGMSG DB "Dispensing...", "$"
DATA ENDS

STK SEGMENT STACK
	 BOS DW 64d DUP(?)
	 TOS LABEL WORD
STK ENDS

CODE SEGMENT PUBLIC 'CODE'
	 ASSUME CS:CODE, DS:DATA, SS:STK
	 ORG 08000H
	 
START:
	 MOV AX, DATA
	 MOV DS, AX
	 MOV AX, STK
	 MOV SS, AX
	 LEA SP, TOS
	 CLI
	 
	 ;8255
	 MOV DX, COM_REG1
	 MOV AL, 89H
	 OUT DX, AL
	 
	 MOV DX, COM_REG2
	 MOV AL, 89H
	 OUT DX, AL
	 
	 ;8253
	 MOV DX, WRITE
	 MOV AL, 38H
	 OUT DX, AL
	 
	 ;8259
	 MOV DX, PIC1
	 MOV AL, ICW1
	 OUT DX, AL
	 
	 	 ;interrupt vector
	 MOV AX, OFFSET ISR4
	 MOV [ES:210H], AX
	 MOV AX, SEG ISR4
	 MOV [ES:212H], AX
	 
	 MOV AX, OFFSET ISR6
	 MOV [ES:218H], AX
	 MOV AX, SEG ISR6
	 MOV [ES:21AH], AX
	 
	 CALL DISPLAY_MENU
	 
	 ;foreground
	 DISPLAY_MENU:
		  MOV AL, 00H
		  MOV FLAG_TEST, AL
		  MOV FLAG_EMERGENCY, AL
		  
		  ;masking testvalve
		  MOV DX, PIC2
		  MOV AL, ICW2
		  OUT DX, AL
		  MOV AL, ICW4
		  OUT DX, AL
		  MOV AL, OCW1_84H
		  OUT DX, AL
		  STI
		  
		  CALL RESET_LED
		  CALL INIT_LCD
		  MENU_COKEL:
			   MOV AL, 80H
			   CALL INST_CTRL
			   LEA SI, MENU1
			   DISPLAY_MENUCOKEL:
				    MOV AL, [SI]
				    CMP AL, "$"
				    JE MENU_COKEM
				    CALL DATA_CTRL
				    INC SI
				    JMP DISPLAY_MENUCOKEL
		  MENU_COKEM:
			   MOV AL, 0C0H
			   CALL INST_CTRL
			   LEA SI, MENU2
			   DISPLAY_MENUCOKEM:
				    MOV AL, [SI]
				    CMP AL, "$"
				    JE MENU_SPRITEL
				    CALL DATA_CTRL
				    INC SI
				    JMP DISPLAY_MENUCOKEM
		  MENU_SPRITEL:
			   MOV AL, 94H
			   CALL INST_CTRL
			   LEA SI, MENU3
			   DISPLAY_MENUSPRITEL:
				    MOV AL, [SI]
				    CMP AL, "$"
				    JE MENU_SPRITEM
				    CALL DATA_CTRL
				    INC SI
				    JMP DISPLAY_MENUSPRITEL
		  MENU_SPRITEM:
			   MOV AL, 0D4H
			   CALL INST_CTRL
			   LEA SI, MENU4
			   DISPLAY_MENUSPRITEM:
				    MOV AL, [SI]
				    CMP AL, "$"
				    JE COKEM
				    CALL DATA_CTRL
				    INC SI
				    JMP DISPLAY_MENUSPRITEM
	 GET_INPUT:
	      MOV AL, FLAG_TEST
		  CMP AL, 2
		  JE VALVE_TEST
		  MOV DX, PORTC
		  IN AL, DX
		  TEST AL, 10H
		  JZ GET_INPUT
		  
		  IN AL, DX
		  AND AL, 0FH
		  
		  CMP AL, 00H
		  JE COKEL
		  CMP AL, 01H
		  JE COKEM
		  CMP AL, 02H
		  JE SPRITEL
		  CMP AL, 04H
		  JE SPRITEM
		  
		  CALL DELAY_1MS
		  JMP GET_INPUT
	 COKEL:
		  MOV DX, PORTD
		  MOV AL, 0001B
		  OUT DX, AL
		  CALL DISPLAY_DISPMSG
		  CALL SET_ISR6
		  CALL TIMER_7S
	 COKEM:
		  MOV DX, PORTD
		  MOV AL, 0010B
		  OUT DX, AL
		  CALL DISPLAY_DISPMSG
		  CALL SET_ISR6
		  CALL TIMER_4S
	 SPRITEL:
		  MOV DX, PORTD
		  MOV AL, 0100B
		  OUT DX, AL
		  CALL DISPLAY_DISPMSG
		  CALL SET_ISR6
		  CALL TIMER_7S
	 SPRITEM:
		  MOV DX, PORTD
		  MOV AL, 1000B
		  OUT DX, AL
		  CALL DISPLAY_DISPMSG
		  CALL SET_ISR6
		  CALL TIMER_4S
	 TIMER_7S:
		  XOR CX, CX
		  MOV CL, 7
		  LOOP_7S:
			   MOV AL, 9DH
			   CALL INST_CTRL
			   MOV AL, 30H
			   ADD AL, CL
			   CALL DATA_CTRL
			   MOV AL, 9EH
			   CALL INST_CTRL
			   MOV AL, 'S'
			   CALL DATA_CTRL
			   CALL TIMER_SET
			   MOV AL, FLAG_EMERGENCY
			   CMP AL, 1
			   JE EMERGENCY_STOP
			   LOOP LOOP_7S
			   JMP DISPLAY_MENU
	 TIMER_4S:
		  XOR CX, CX
		  MOV CL, 4
		  LOOP_4S:
			   MOV AL, 9DH
			   CALL INST_CTRL
			   MOV AL, 30H
			   ADD AL, CL
			   CALL DATA_CTRL
			   MOV AL, 9EH
			   CALL INST_CTRL
			   MOV AL, 'S'
			   CALL DATA_CTRL
			   CALL TIMER_SET
			   MOV AL, FLAG_EMERGENCY
			   CMP AL, 1
			   JE EMERGENCY_STOP
			   LOOP LOOP_4S
			   JMP DISPLAY_MENU
	 INST_CTRL:
		  PUSH AX
		  MOV DX, PORTA
		  OUT DX, AL
		  MOV DX, PORTB
		  MOV AL, 02H
		  OUT DX, AL
		  CALL DELAY_1MS
		  MOV DX, PORTB
		  MOV AL, 00H
		  OUT DX, AL
		  POP AX
		  RET
	DATA_CTRL:
		  PUSH AX
		  MOV DX, PORTA
		  OUT DX, AL
		  MOV DX, PORTB
		  MOV AL, 03H
		  OUT DX, AL
		  CALL DELAY_1MS
		  MOV DX, PORTB
		  MOV AL, 01H
		  OUT DX, AL
		  POP AX
		  RET
	INIT_LCD:
		  MOV AL, 38H
		  CALL INST_CTRL
		  MOV AL, 08H
		  CALL INST_CTRL
		  MOV AL, 01H
		  CALL INST_CTRL
		  MOV AL, 06H
		  CALL INST_CTRL
		  MOV AL, 0CH
		  CALL INST_CTRL
		  RET
	DELAY_1MS:
		   MOV BX, 02CAH
		   LOOP_DELAY1MS:
			   DEC BX
			   NOP
			   JNZ LOOP_DELAY1MS
			   RET
	 RESET_LED:
		  MOV DX, PORTD
		  MOV AL, 0
		  OUT DX, AL
		  RET
	 TIMER_SET:
		  MOV DX, TIMER
		  MOV AL, 0A0H
		  OUT DX, AL
		  MOV AL, 0FH
		  OUT DX, AL
	 SET_ISR6:
		  ;mask e!stop
		  MOV DX, PIC2
		  MOV AL, ICW2
		  OUT DX, AL
		  MOV AL, ICW4
		  OUT DX, AL
		  MOV AL, OCW1_86H
		  OUT DX, AL
		  STI
		  RET
	 VALVE_TEST:
		  CALL INIT_LCD
		  
		  MOV AL, 0
		  MOV FLAG_TEST, AL
		  
		  CALL SET_ISR6
		  
		  MOV DX, PORTD
		  MOV AL, 0
		  OUT DX, AL
		  
		  CALL DISPLAY_MSG1
		  
		  CLI
	 EMERGENCY_STOP:
		  XOR CX, CX
		  MOV AL, 0
		  MOV FLAG_EMERGENCY, AL
		  
		  CALL DISPLAY_MSG2
		  CALL RESET_LED
		  MOV CL, 02H
		  MSG_LOOP:
			   CALL TIMER_SET
			   LOOP MSG_LOOP
			   JMP DISPLAY_MENU
	 DISPLAY_DISPMSG:
		  CALL INIT_LCD
		  MOV AL, 0C4H
		  LEA SI, DISPENSINGMSG
		  LOOP_MSG:
			   MOV AL, [SI]
			   CMP AL, "$"
			   JE EXIT_LOOPMSG
			   CALL DATA_CTRL
			   INC SI
			   JMP LOOP_MSG
			   EXIT_LOOPMSG:
				    RET
	 DISPLAY_MSG1:
		  CALL INIT_LCD
		  MOV AL, 0C1H
		  LEA SI, MSG1
		  LOOP_MSG1:
			   MOV AL, [SI]
			   CMP AL, "$"
			   JE EXIT_LOOPMSG1
			   CALL DATA_CTRL
			   INC SI
			   JMP LOOP_MSG1
			   EXIT_LOOPMSG1:
				    RET
	 DISPLAY_MSG2:
		  CALL INIT_LCD
		  MOV AL, 0C1H
		  LEA SI, MSG2
		  LOOP_MSG2:
			   MOV AL, [SI]
			   CMP AL, "$"
			   JE EXIT_LOOPMSG2
			   CALL DATA_CTRL
			   INC SI
			   JMP LOOP_MSG2
			   EXIT_LOOPMSG2:
				    RET
CODE ENDS
END START
	 